#Versão docker-compose
version: "3.7"

#especificar containers que serao utilizados
services:

  #nome para identificar o serviço(container)
  db:
    #nome da imagem docker hub
    image: mongo
    #nome que será dado ao container
    container_name: mongo-container
    #declaração de volumes utilizado pelo container
    volumes:
      - /db/data:/data/db
    restart: always
    #bind de portas
    ports:
      - "27017:27017"

  service:
    image: 160982/microservice-depesas
    container_name: microservice-despesa
    restart: always
    #Especifica que o serviço "db" é acessável pelo serviço "poc" através do alias mongo-container(que é utilizado para comunicação no application.properties)
    links:
      - "db:mongo-container"
    ports:
      - "8080:8080"
    #Especifica que a aplicação depende do serviço db, ou seja, db sobe primeiro
    depends_on:
      - db

  front:
    image: 160982/front-controle-financeiro
    container_name: frontend-controle-financeiro
    restart: always
    links: 
      - "service:microservice-despesa"
    ports:
      - "4200:80"
    depends_on:
      - db
      - service

